# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d7aa86f46c0891886b8a082e54b0c9b1067a2027c013bebe5c7a2c82204578e337845e53082f2e8721f34ed7af740824dee2a9718da3f45a7e034ea6e0a7809b

test:
  secret_key_base: 943f377cc86ef49206e81e3f306659e09f184a9a418a449149ea871f32d262d45a77ecd614491e63647ad7fd055cd8906dae27cdbe66762b2302aae3cce4a372

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
